apiVersion: apps/v1
kind: Deployment
metadata:
  name:  shoppingapi-deployment
  labels:
    app:  shoppingapi
spec:
  selector:
    matchLabels:
      app: shoppingapi
  replicas: 1
  template:
    metadata:
      labels:
        app:  shoppingapi
    spec:
      containers:
        - name:  shoppingapi
          image:  kelvinlam/shoppingapi:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
          ports:
            - containerPort:  80

---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  selector:
    app: shoppingapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 31000